## Task:
* Create arrays with all the data types available in numpy

#### NumPy Data Types

* integer
* boolean
* unsigned integer
* float
* complex float
* timedelta
* datetime
* object
* string
* unicode string
* fixed chunk of memory for other type ( void )

In [1]:
import numpy as np

In [2]:
#integer
x = np.array([1,2,3,4,5])
print(x)
x.dtype

[1 2 3 4 5]


dtype('int32')

In [3]:
#boolean
x = np.array([0,1,2,3,4,5], dtype='bool_')
print(x)
x.dtype

[False  True  True  True  True  True]


dtype('bool')

In [4]:
#unsigned integer
x= np.array([64454], dtype='uint16')
print(x)
x.dtype

[64454]


dtype('uint16')

In [5]:
#float
x= np.array([1.2, 2.3, 3.4, 4.5, 5.6])
print(x)
x.dtype

[1.2 2.3 3.4 4.5 5.6]


dtype('float64')

In [6]:
#complex float
x = np.array([1+2j, 2+3j, 4+5j, 5+6j])
print(x)
x.dtype

[1.+2.j 2.+3.j 4.+5.j 5.+6.j]


dtype('complex128')

In [7]:
#timedelta
x=np.timedelta64(8, 'D')
print(x)
x.dtype

8 days


dtype('<m8[D]')

In [8]:
#datetime
x=np.array(['2011-02-11', '2012-03-12', '2013-04-13'], dtype='datetime64')
x

array(['2011-02-11', '2012-03-12', '2013-04-13'], dtype='datetime64[D]')

In [9]:
#object
x = np.array([1,3,5,7], dtype='O')
x

array([1, 3, 5, 7], dtype=object)

In [10]:
#String
x = np.array(['Hello', 'Good', 'Morning', 'Everyone!'])
print(x)
x.dtype

['Hello' 'Good' 'Morning' 'Everyone!']


dtype('<U9')

In [11]:
#unicode string
x = np.array([u'\u03bcm', u'\u2202r', u'\u2206\u03bb'], dtype='U')
x

array(['μm', '∂r', '∆λ'], dtype='<U2')

In [ ]:
#void
x=np.void([], dtype='V')
x